apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: openshift-hugepages
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Configuration for hugepages
      include=openshift-node
      [vm]
      transparent_hugepages=never
      [sysctl]
      vm.nr_hugepages=16
    name: openshift-hugepages
  recommend:
  - machineConfigLabels:
      machineconfiguration.openshift.io/role: "infra"
    priority: 20
    profile: openshift-hugepages"
